ktor:
  application:
    modules:
      - ru.jerael.booktracker.backend.ApplicationKt.module
  deployment:
    port: 8080
  db:
    url: $DB_URL
    driver: "org.postgresql.Driver"
    user: $DB_USER
    password: $DB_PASSWORD
  storage:
    persistentPath: "$PERSISTENT_STORAGE_PATH:./storage"
    baseUrl: $STORAGE_BASE_URL
  smtp:
    host: $SMTP_HOST
    port: $SMTP_PORT
    user: $SMTP_USER
    password: $SMTP_PASSWORD
    from: $SMTP_FROM
    ssl: $SMTP_SSL_ENABLED
  otp:
    length: 6
    validityMinutes: 10
  jwt:
    secret: $JWT_SECRET
    issuer: $JWT_ISSUER
    audience: $JWT_AUDIENCE
    realm: $JWT_REALM
    accessExpiresInMinutes: 15
    refreshExpiresInDays: 30