name: Android and Backend tests

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

permissions:
  contents: read
  pull-requests: read

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      android: ${{ steps.filter.outputs.android }}
    steps:
      - uses: actions/checkout@v5
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            backend:
              - 'backend/**'
              - 'build.gradle.kts'
              - 'settings.gradle.kts'
              - 'gradle.properties'
              - 'gradle/**'
              - '.github/workflows/ci.yml'
            android:
              - 'android/**'
              - 'build.gradle.kts'
              - 'settings.gradle.kts'
              - 'gradle.properties'
              - 'gradle/**'
              - '.github/workflows/ci.yml'

  backend-test:
    needs: changes
    if: needs.changes.outputs.backend == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Create secrets.properties
        run: echo "BACKEND_BASE_URL=${{ secrets.BACKEND_BASE_URL }}" > secrets.properties

      - name: Create .env
        run: echo "STORAGE_BASE_URL=${{ secrets.STORAGE_BASE_URL }}" > .env

      - name: Run Backend Tests
        run: ./gradlew :backend:clean :backend:test

  android-test:
    needs: changes
    if: needs.changes.outputs.android == 'true'
    runs-on: ubuntu-latest
    env:
      EMULATOR_API_LEVEL: 29
    steps:
      - uses: actions/checkout@v5

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: AVD cache
        uses: actions/cache@v4
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ env.EMULATOR_API_LEVEL }}

      - name: Enable KVM group perms
        run: |
            echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
            sudo udevadm control --reload-rules
            sudo udevadm trigger --name-match=kvm

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Create secrets.properties
        run: echo "BACKEND_BASE_URL=${{ secrets.BACKEND_BASE_URL }}" > secrets.properties

      - name: Run Android Unit Tests
        run: ./gradlew :android:app:testDebugUnitTest

      - name: Run Android Instrumented Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ env.EMULATOR_API_LEVEL }}
          script: ./gradlew :android:app:connectedDebugAndroidTest